import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { issueDeploymentIdentity, runCanaryCutover, verifyCandidatePortIsolation, verifyEquivalentRollbackReadiness } from "./canaryCutover.js";

const sha = (value: string | Buffer): string => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const canonical = (value: unknown): string => JSON.stringify(value, (_key, item: unknown) => item && typeof item === "object" && !Array.isArray(item) ? Object.fromEntries(Object.entries(item).sort(([a], [b]) => a.localeCompare(b))) : item);
const projectPath = "/absolute/project", compiledPath = "/absolute/compiled";
const ready = (run = "candidate", fingerprint = "sf1:aaaaaaaaaaaa") => ({ version: "spawnfile.up-receipt.v1", run_id: run, fingerprint, deployment: { name: run, container_ids: [`${run}-container`] }, readiness: { state: "running", moltnet_base_url: null }, compiled_schedule: [{ agent: "agent:a", cron: "0 5 * * *" }], engines: [{ agent: "agent:a", engine: "codex" }], organization_ready: { version: "spawnfile.organization-ready.v1", state: "ready", code: "organization_ready", run_id: run, unit_id: "unit-a", compile_fingerprint: fingerprint, world_binding_digest: `sha256:${"a".repeat(64)}` } });
const identity = (receipt: ReturnType<typeof ready>, mode: "project" | "image" = "project") => ({ version: "spawnfile.deployment-identity.v1", run_id: receipt.run_id, fingerprint: receipt.fingerprint, deployment_name: receipt.deployment.name, deployment_mode: mode, image_id: `sha256:${"b".repeat(64)}`, organization_unit_id: receipt.organization_ready.unit_id, organization_compile_fingerprint: receipt.organization_ready.compile_fingerprint, organization_world_binding_digest: receipt.organization_ready.world_binding_digest, topology_sha256: sha(canonical({ compiled_schedule: receipt.compiled_schedule, engines: receipt.engines, moltnet_release: null })) });

describe("generic canary cutover", () => {
  it("reserves a nonce, rejects stale receipts, and reconciles ingress before a final decision", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "spawnfile-cutover-")); try {
      expect(() => verifyCandidatePortIsolation({ published_ports: [8080] }, { published_ports: [8080] })).toThrow(/isolated/u);
      expect(() => verifyCandidatePortIsolation({ published_ports: [] }, { published_ports: [18080, 18080] })).toThrow(/isolated/u);
      expect(() => verifyCandidatePortIsolation(
        { published_ports: [8080], persistent_mounts: [{ id: "provider-realm" }] },
        { published_ports: [18080], persistent_mounts: [{ id: "provider-realm", lifecycle: "exclusive-reattach" }] }
      )).toThrow(/stop-and-reattach/u);
      const live = path.join(root, "live.json"), candidate = path.join(root, "candidate.json"), readinessPath = path.join(root, "ready.json"), ingress = path.join(root, "ingress.json"), decision = path.join(root, "decision.json"), transaction = path.join(root, "transaction.json");
      const receipt = ready(), readinessBytes = Buffer.from(`${JSON.stringify(receipt)}\n`), expected = identity(receipt), operationNonce = "1".repeat(32);
      await writeFile(live, JSON.stringify({ published_ports: [8080] })); await writeFile(candidate, JSON.stringify({ published_ports: [18080] })); await writeFile(readinessPath, readinessBytes);
      await expect(issueDeploymentIdentity(readinessPath, "project", "docker", async () => expected.image_id)).resolves.toEqual(expected);
      const input = { liveReportPath: live, candidateReportPath: candidate, readinessPath, expectedIdentity: expected, dockerCommand: "docker", nonce: operationNonce, transactionPath: transaction, ingressCommand: "switch", ingressArgs: [], ingressReceiptPath: ingress, teardownCommand: "spawnfile", teardownArgs: ["down", projectPath, "--compiled", compiledPath, "--deployment", "live", "--force", "--json", "--lifecycle-invocation", `lci_canary_${operationNonce}`], teardownPolicy: "force" as const, teardownProjectPath: projectPath, teardownCompiledPath: compiledPath, decisionReceiptPath: decision, fromDeployment: "live", toDeployment: "candidate" };
      const calls: string[] = []; let logicalTeardowns = 0, tornDown = false, teardownArgv: string[] = []; const runner = async (command: string, args: string[]) => { calls.push(command); if (command === "switch") { await writeFile(ingress, JSON.stringify({ version: "spawnfile.ingress-cutover-receipt.v1", state: "switched", nonce: operationNonce, from_deployment: "live", to_deployment: "candidate", target_run_id: "candidate", readiness_sha256: sha(readinessBytes) })); return; } teardownArgv = args; if (!tornDown) { tornDown = true; logicalTeardowns += 1; } return JSON.stringify({ version: "spawnfile.down-receipt.v1", deployment: "live", units_stopped: ["live-container"], retained_volumes: ["state"], errors: [] }); };
      await expect(runCanaryCutover(input, runner, async () => expected.image_id)).resolves.toMatchObject({ decision: "cutover", target_run_id: "candidate" }); expect(calls).toEqual(["switch", "spawnfile"]); expect(teardownArgv.slice(0, 4)).toEqual(["down", projectPath, "--compiled", compiledPath]);
      await expect(runCanaryCutover(input, runner, async () => expected.image_id)).resolves.toEqual(JSON.parse(await readFile(decision, "utf8"))); expect(calls).toEqual(["switch", "spawnfile"]);
      const checkpointPath = `${transaction}.teardown-complete`, checkpointBytes = await readFile(checkpointPath); await rm(checkpointPath); await expect(runCanaryCutover(input, runner, async () => expected.image_id)).rejects.toThrow(/without its teardown checkpoint/u); await writeFile(checkpointPath, checkpointBytes);
      await rm(decision); await expect(runCanaryCutover(input, runner, async () => expected.image_id)).resolves.toMatchObject({ decision: "cutover" }); expect(calls).toEqual(["switch", "spawnfile"]);
      await rm(decision); await rm(`${transaction}.teardown-complete`); await rm(`${transaction}.teardown-receipt`); await expect(runCanaryCutover(input, runner, async () => expected.image_id)).resolves.toMatchObject({ decision: "cutover" }); expect(calls).toEqual(["switch", "spawnfile", "spawnfile"]); expect(logicalTeardowns).toBe(1);
      const validDecision = JSON.parse(await readFile(decision, "utf8")); await writeFile(decision, JSON.stringify({ ...validDecision, target_run_id: "other" })); await expect(runCanaryCutover(input, runner, async () => expected.image_id)).rejects.toThrow(/does not match/u); const { teardown_checkpoint_sha256: _missing, ...missingDigest } = validDecision; await writeFile(decision, JSON.stringify(missingDigest)); await expect(runCanaryCutover(input, runner, async () => expected.image_id)).rejects.toThrow(); await writeFile(decision, JSON.stringify({ ...validDecision, down_receipt_sha256: `sha256:${"0".repeat(64)}` })); await expect(runCanaryCutover(input, runner, async () => expected.image_id)).rejects.toThrow(/does not match/u); await writeFile(decision, JSON.stringify(validDecision));
      const staleRoot = path.join(root, "stale"); await writeFile(staleRoot, "stale"); await expect(runCanaryCutover({ ...input, transactionPath: path.join(root, "new-transaction"), ingressReceiptPath: staleRoot, decisionReceiptPath: path.join(root, "new-decision") }, runner, async () => expected.image_id)).rejects.toThrow(/Stale/u);
      await expect(runCanaryCutover({ ...input, nonce: "2".repeat(32), teardownArgs: ["down", projectPath, "--compiled", compiledPath, "--deployment", "live", "--force", "--json", "--lifecycle-invocation", `lci_canary_${"2".repeat(32)}`] }, runner, async () => expected.image_id)).rejects.toThrow(/authority/u);
    } finally { await rm(root, { recursive: true, force: true }); }
  });
  it("binds rollback readiness to the exact prior organization, image-independent topology, and run", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "spawnfile-rollback-")); try { const prior = ready("live", "sf1:bbbbbbbbbbbb"), file = path.join(root, "ready.json"); await writeFile(file, JSON.stringify(prior)); await expect(verifyEquivalentRollbackReadiness(file, identity(prior, "image"))).resolves.toBeUndefined(); await expect(verifyEquivalentRollbackReadiness(file, { ...identity(prior, "image"), run_id: "other" })).rejects.toThrow(/exact intended/u); const noWorld = { ...prior, organization_ready: { ...prior.organization_ready, world_binding_digest: null } }, noWorldPath = path.join(root, "no-world.json"); await writeFile(noWorldPath, JSON.stringify(noWorld)); await expect(issueDeploymentIdentity(noWorldPath, "project", "docker", async () => `sha256:${"b".repeat(64)}`)).resolves.toMatchObject({ organization_world_binding_digest: null }); } finally { await rm(root, { recursive: true, force: true }); }
  });
  it("fails closed on image, container, bounds, and nonce drift", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "spawnfile-cutover-hostile-")); try {
      const live = path.join(root, "live.json"), candidate = path.join(root, "candidate.json"), readinessPath = path.join(root, "ready.json"), receipt = ready(), bytes = Buffer.from(JSON.stringify(receipt)), expected = identity(receipt);
      await writeFile(live, JSON.stringify({ published_ports: [80] })); await writeFile(candidate, JSON.stringify({ published_ports: [81] })); await writeFile(readinessPath, bytes);
      const base = { liveReportPath: live, candidateReportPath: candidate, readinessPath, expectedIdentity: expected, dockerCommand: "docker", nonce: "3".repeat(32), transactionPath: path.join(root, "transaction"), ingressCommand: "switch", ingressArgs: [], ingressReceiptPath: path.join(root, "ingress"), teardownCommand: "spawnfile", teardownArgs: ["down", projectPath, "--compiled", compiledPath, "--deployment", "live", "--force", "--json", "--lifecycle-invocation", `lci_canary_${"3".repeat(32)}`], teardownPolicy: "force" as const, teardownProjectPath: projectPath, teardownCompiledPath: compiledPath, decisionReceiptPath: path.join(root, "decision"), fromDeployment: "live", toDeployment: "candidate" };
      await expect(runCanaryCutover({ ...base, ingressArgs: Array(33).fill("x") }, async () => {}, async () => expected.image_id)).rejects.toThrow(/bounds/u);
      await expect(runCanaryCutover({ ...base, teardownPolicy: "export" }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      await expect(runCanaryCutover({ ...base, teardownPolicy: "export", teardownArgs: ["down", "--deployment", "live", "--export-to"] }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      await expect(runCanaryCutover({ ...base, teardownArgs: ["down", "--json"] }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      await expect(runCanaryCutover({ ...base, teardownArgs: base.teardownArgs.map((value, index) => index === 5 ? "other" : value) }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      await expect(runCanaryCutover({ ...base, teardownArgs: [...base.teardownArgs, "--force"] }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      await expect(runCanaryCutover({ ...base, teardownArgs: [...base.teardownArgs, "--timeout", "1"] }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      await expect(runCanaryCutover({ ...base, teardownProjectPath: "relative/project" }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      const alternate = "/absolute/../absolute/project"; await expect(runCanaryCutover({ ...base, teardownProjectPath: alternate, teardownArgs: base.teardownArgs.map((value, index) => index === 1 ? alternate : value) }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      const trailing = `${compiledPath}/`; await expect(runCanaryCutover({ ...base, teardownCompiledPath: trailing, teardownArgs: base.teardownArgs.map((value, index) => index === 3 ? trailing : value) }, async () => {}, async () => expected.image_id)).rejects.toThrow(/canonical/u);
      await expect(runCanaryCutover(base, async () => {}, async () => `sha256:${"c".repeat(64)}`)).rejects.toThrow(/image/u);
      await expect(issueDeploymentIdentity(readinessPath, "project", "docker", async (_command, args) => args.at(-1) === "candidate-container" ? expected.image_id : `sha256:${"c".repeat(64)}`)).resolves.toMatchObject({ image_id: expected.image_id });
      const split = { ...receipt, deployment: { ...receipt.deployment, container_ids: ["one", "two"] } }, splitPath = path.join(root, "split"); await writeFile(splitPath, JSON.stringify(split)); await expect(issueDeploymentIdentity(splitPath, "project", "docker", async (_command, args) => args.at(-1) === "one" ? expected.image_id : `sha256:${"c".repeat(64)}`)).rejects.toThrow(/one exact image/u);
      const noContainers = { ...receipt, deployment: { ...receipt.deployment, container_ids: [] } }, noContainersPath = path.join(root, "no-containers"); await writeFile(noContainersPath, JSON.stringify(noContainers)); await expect(issueDeploymentIdentity(noContainersPath, "project", "docker", async () => expected.image_id)).rejects.toThrow(/identity-ready/u);
      await expect(runCanaryCutover({ ...base, readinessPath: noContainersPath, transactionPath: path.join(root, "empty-transaction") }, async () => {}, async () => expected.image_id)).rejects.toThrow(/no image-bearing/u);
      const noEngines = { ...receipt }; delete (noEngines as Partial<typeof receipt>).engines; const noEnginesPath = path.join(root, "no-engines"); await writeFile(noEnginesPath, JSON.stringify(noEngines)); await expect(issueDeploymentIdentity(noEnginesPath, "project", "docker", async () => expected.image_id)).resolves.toMatchObject({ run_id: "candidate" });
      const wrongIngress = async () => { await writeFile(base.ingressReceiptPath, JSON.stringify({ version: "spawnfile.ingress-cutover-receipt.v1", state: "switched", nonce: "4".repeat(32), from_deployment: "live", to_deployment: "candidate", target_run_id: "candidate", readiness_sha256: sha(bytes) })); };
      await expect(runCanaryCutover(base, wrongIngress, async () => expected.image_id)).rejects.toThrow(/nonce/u);
      const fake = { ...base, nonce: "5".repeat(32), transactionPath: path.join(root, "fake-transaction"), ingressReceiptPath: path.join(root, "fake-ingress"), decisionReceiptPath: path.join(root, "fake-decision"), teardownArgs: ["down", projectPath, "--compiled", compiledPath, "--deployment", "live", "--force", "--json", "--lifecycle-invocation", `lci_canary_${"5".repeat(32)}`] }; await expect(runCanaryCutover(fake, async (command) => { if (command === "switch") { await writeFile(fake.ingressReceiptPath, JSON.stringify({ version: "spawnfile.ingress-cutover-receipt.v1", state: "switched", nonce: fake.nonce, from_deployment: "live", to_deployment: "candidate", target_run_id: "candidate", readiness_sha256: sha(bytes) })); return; } return JSON.stringify({ version: "spawnfile.down-receipt.v1", deployment: "other", units_stopped: [], retained_volumes: [], errors: [] }); }, async () => expected.image_id)).rejects.toThrow(/exact teardown/u);
    } finally { await rm(root, { recursive: true, force: true }); }
  });
});
