import path from "node:path";

import type { Secret } from "../manifest/index.js";
import type { ContainerReport } from "../report/index.js";
import {
  createRuntimeInstallRecipe,
  getRuntimeAdapter
} from "../runtime/index.js";
import type {
  ContainerTarget,
  ContainerTargetInput,
  EmittedFile,
  RuntimeContainerMeta
} from "../runtime/index.js";
import { SpawnfileError } from "../shared/index.js";

import type { CompilePlan, ResolvedAgentNode, ResolvedTeamNode } from "./types.js";

const CONFIG_FILE_PLACEHOLDER = "<config-file>";
const CONTAINER_ROOTFS_ROOT = "container/rootfs";
const GATEWAY_PORT_PLACEHOLDER = "<gateway-port>";
const INSTANCE_ROOT_PLACEHOLDER = "<instance-root>";
const WORKSPACE_PLACEHOLDER = "<workspace-path>";

const MODEL_PROVIDER_ENV_VARS = new Map<string, string>([
  ["anthropic", "ANTHROPIC_API_KEY"],
  ["google", "GOOGLE_API_KEY"],
  ["groq", "GROQ_API_KEY"],
  ["mistral", "MISTRAL_API_KEY"],
  ["openai", "OPENAI_API_KEY"],
  ["openrouter", "OPENROUTER_API_KEY"],
  ["xai", "XAI_API_KEY"]
]);

interface ContainerEnvVariable {
  description: string;
  name: string;
  required: boolean;
}

interface RuntimeTargetPlan {
  id: string;
  instancePaths: {
    configPath: string;
    homePath?: string;
    workspacePath: string;
  };
  meta: RuntimeContainerMeta;
  port?: number;
  runtimeName: string;
  runtimeRoot: string;
  targetFiles: EmittedFile[];
}

export interface CompiledNodeArtifact {
  emittedFiles: EmittedFile[];
  kind: "agent" | "team";
  runtimeName: string | null;
  slug: string;
  value: ResolvedAgentNode | ResolvedTeamNode;
}

export interface GeneratedContainerArtifacts {
  executablePaths: string[];
  files: EmittedFile[];
  report: ContainerReport;
}

const shellQuote = (value: string): string => `'${value.replace(/'/g, `'\"'\"'`)}'`;

const createDefaultTargets = (inputs: ContainerTargetInput[]): ContainerTarget[] =>
  inputs.map((input) => ({
    files: input.emittedFiles,
    id: `${input.kind}-${input.slug}`
  }));

const createEnvVariableMap = (
  compiledNodes: CompiledNodeArtifact[],
  runtimePlans: RuntimeTargetPlan[]
): Map<string, ContainerEnvVariable> => {
  const variables = new Map<string, ContainerEnvVariable>();

  const register = (name: string, required: boolean, description: string): void => {
    const current = variables.get(name);
    if (!current) {
      variables.set(name, { description, name, required });
      return;
    }

    variables.set(name, {
      ...current,
      required: current.required || required
    });
  };

  const registerSecret = (secret: Secret): void => {
    register(secret.name, secret.required, "Declared in Spawnfile secrets");
  };

  const registerProvider = (provider: string): void => {
    const envName =
      MODEL_PROVIDER_ENV_VARS.get(provider) ??
      `${provider.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_API_KEY`;
    register(envName, true, `Model provider auth for ${provider}`);
  };

  for (const node of compiledNodes) {
    if (node.value.kind === "agent") {
      for (const secret of node.value.secrets) {
        registerSecret(secret);
      }

      const executionModel = node.value.execution?.model;
      if (executionModel?.primary) {
        registerProvider(executionModel.primary.provider);
      }
      for (const fallback of executionModel?.fallback ?? []) {
        registerProvider(fallback.provider);
      }
      continue;
    }

    for (const secret of node.value.shared.secrets) {
      registerSecret(secret);
    }
  }

  for (const runtimePlan of runtimePlans) {
    for (const variable of runtimePlan.meta.env ?? []) {
      register(variable.name, variable.required, variable.description);
    }
  }

  return variables;
};

const renderEnvExample = (variables: ContainerEnvVariable[]): string => {
  if (variables.length === 0) {
    return "# No environment variables were detected during compile.\n";
  }

  const lines = ["# Generated by spawnfile compile", ""];

  const requiredVariables = variables.filter((variable) => variable.required);
  const optionalVariables = variables.filter((variable) => !variable.required);

  if (requiredVariables.length > 0) {
    lines.push("# Required");
    for (const variable of requiredVariables) {
      lines.push(`# ${variable.description}`);
      lines.push(`${variable.name}=`);
      lines.push("");
    }
  }

  if (optionalVariables.length > 0) {
    lines.push("# Optional");
    for (const variable of optionalVariables) {
      lines.push(`# ${variable.description}`);
      lines.push(`${variable.name}=`);
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
};

const assertTargetHasConfig = (
  runtimeName: string,
  targetId: string,
  meta: RuntimeContainerMeta,
  files: EmittedFile[]
): void => {
  if (!files.some((file) => file.path === meta.configFileName)) {
    throw new SpawnfileError(
      "runtime_error",
      `Container target ${targetId} for ${runtimeName} is missing ${meta.configFileName}`
    );
  }
};

const replaceContainerPathTemplate = (
  template: string,
  instanceRoot: string,
  configFileName: string
): string =>
  template
    .replaceAll(INSTANCE_ROOT_PLACEHOLDER, instanceRoot)
    .replaceAll(CONFIG_FILE_PLACEHOLDER, configFileName);

const resolveInstancePaths = (
  runtimeName: string,
  targetId: string,
  meta: RuntimeContainerMeta
): { configPath: string; homePath?: string; workspacePath: string } => {
  const instanceRoot = `/var/lib/spawnfile/instances/${runtimeName}/${targetId}`;

  return {
    configPath: replaceContainerPathTemplate(
      meta.instancePaths.configPathTemplate,
      instanceRoot,
      meta.configFileName
    ),
    homePath: meta.instancePaths.homePathTemplate
      ? replaceContainerPathTemplate(
          meta.instancePaths.homePathTemplate,
          instanceRoot,
          meta.configFileName
        )
      : undefined,
    workspacePath: replaceContainerPathTemplate(
      meta.instancePaths.workspacePathTemplate,
      instanceRoot,
      meta.configFileName
    )
  };
};

const createRuntimeTargetPlans = async (
  plan: CompilePlan,
  compiledNodes: CompiledNodeArtifact[]
): Promise<RuntimeTargetPlan[]> => {
  const runtimeNames = Object.keys(plan.runtimes).sort();
  const runtimePlans: RuntimeTargetPlan[] = [];

  for (const runtimeName of runtimeNames) {
    const adapter = getRuntimeAdapter(runtimeName);
    const recipe = await createRuntimeInstallRecipe(runtimeName);
    const targetInputs = compiledNodes
      .filter((node) => node.runtimeName === runtimeName && node.emittedFiles.length > 0)
      .map(
        (node): ContainerTargetInput => ({
          emittedFiles: node.emittedFiles,
          id: `${node.kind}:${node.slug}`,
          kind: node.kind,
          slug: node.slug,
          value: node.value
        })
      );

    const targets =
      (await adapter.createContainerTargets?.(targetInputs)) ??
      createDefaultTargets(targetInputs);

    targets.forEach((target, index) => {
      assertTargetHasConfig(runtimeName, target.id, adapter.container, target.files);
      runtimePlans.push({
        id: target.id,
        instancePaths: resolveInstancePaths(runtimeName, target.id, adapter.container),
        meta: adapter.container,
        port: adapter.container.port ? adapter.container.port + index : undefined,
        runtimeName,
        runtimeRoot: recipe.runtimeRoot,
        targetFiles: target.files
      });
    });
  }

  return runtimePlans;
};

const renderDockerfile = async (runtimePlans: RuntimeTargetPlan[]): Promise<string> => {
  const runtimeNames = [...new Set(runtimePlans.map((plan) => plan.runtimeName))];
  const runtimeRecipes = await Promise.all(
    runtimeNames.map((runtimeName) => createRuntimeInstallRecipe(runtimeName))
  );

  const firstRuntimeMeta = runtimePlans[0]?.meta;
  const usesMultipleRuntimes = runtimeNames.length > 1;
  const needsNodeSetup = runtimeNames.some(
    (runtimeName) => runtimeName === "openclaw" || runtimeName === "tinyclaw"
  );

  const baseImage = usesMultipleRuntimes
    ? "golang:1.25-bookworm"
    : (firstRuntimeMeta?.standaloneBaseImage ?? "node:22-bookworm-slim");
  const systemDeps = [
    ...new Set(
      runtimePlans.flatMap((plan) => plan.meta.systemDeps).concat(usesMultipleRuntimes && needsNodeSetup ? ["curl"] : [])
    )
  ].sort();
  const exposedPorts = [...new Set(runtimePlans.flatMap((plan) => (plan.port ? [plan.port] : [])))].sort(
    (left, right) => left - right
  );

  const lines = [`FROM ${baseImage}`, "", "WORKDIR /opt/spawnfile"];

  if (systemDeps.length > 0) {
    lines.push(
      `RUN apt-get update && apt-get install -y --no-install-recommends ${systemDeps.join(" ")} && rm -rf /var/lib/apt/lists/*`,
      ""
    );
  }

  if (usesMultipleRuntimes && needsNodeSetup) {
    lines.push(
      "RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && apt-get install -y --no-install-recommends nodejs && rm -rf /var/lib/apt/lists/*",
      ""
    );
  }

  if (needsNodeSetup) {
    lines.push("RUN corepack enable", "");
  }

  for (const recipe of runtimeRecipes) {
    for (const command of recipe.commands) {
      lines.push(`RUN ${command}`);
    }
    lines.push("");
  }

  lines.push(
    "COPY container/rootfs/ /",
    "COPY .env.example /opt/spawnfile/.env.example",
    'COPY entrypoint.sh /opt/spawnfile/entrypoint.sh',
    "RUN chmod +x /opt/spawnfile/entrypoint.sh"
  );

  if (exposedPorts.length > 0) {
    lines.push(`EXPOSE ${exposedPorts.join(" ")}`);
  }

  lines.push('ENTRYPOINT ["/opt/spawnfile/entrypoint.sh"]');
  return `${lines.join("\n").trimEnd()}\n`;
};

const createEnvironmentAssignments = (plan: RuntimeTargetPlan): string[] => {
  const envAssignments: string[] = [];

  if (plan.meta.homeEnv && plan.instancePaths.homePath) {
    envAssignments.push(`${plan.meta.homeEnv}=${shellQuote(plan.instancePaths.homePath)}`);
  }

  if (plan.meta.configPathEnv) {
    envAssignments.push(`${plan.meta.configPathEnv}=${shellQuote(plan.instancePaths.configPath)}`);
  }

  if (plan.meta.portEnv && plan.port) {
    envAssignments.push(`${plan.meta.portEnv}=${shellQuote(String(plan.port))}`);
  }

  for (const [name, value] of Object.entries(plan.meta.staticEnv ?? {}).sort(([left], [right]) =>
    left.localeCompare(right)
  )) {
    envAssignments.push(`${name}=${shellQuote(value)}`);
  }

  return envAssignments;
};

const resolveStartCommand = (plan: RuntimeTargetPlan): string[] =>
  plan.meta.startCommand
    .map((token) =>
      token
        .replace("<runtime-root>", plan.runtimeRoot)
        .replace("<port>", plan.port ? String(plan.port) : "")
    )
    .filter((token) => token.length > 0);

const createRootfsFiles = (runtimePlans: RuntimeTargetPlan[]): EmittedFile[] =>
  runtimePlans.flatMap((plan) =>
    plan.targetFiles.map((file) => {
      if (file.path === plan.meta.configFileName) {
        return {
          content: file.content
            .replaceAll(WORKSPACE_PLACEHOLDER, plan.instancePaths.workspacePath)
            .replaceAll(
              `"${GATEWAY_PORT_PLACEHOLDER}"`,
              plan.port ? String(plan.port) : "0"
            )
            .replaceAll(GATEWAY_PORT_PLACEHOLDER, plan.port ? String(plan.port) : ""),
          path: `${CONTAINER_ROOTFS_ROOT}${plan.instancePaths.configPath}`
        };
      }

      if (file.path.startsWith("workspace/")) {
        const relativeWorkspacePath = file.path.slice("workspace/".length);
        return {
          content: file.content,
          path: `${CONTAINER_ROOTFS_ROOT}${path.posix.join(
            plan.instancePaths.workspacePath,
            relativeWorkspacePath
          )}`
        };
      }

      throw new SpawnfileError(
        "runtime_error",
        `Container target ${plan.id} for ${plan.runtimeName} emitted unsupported path ${file.path}`
      );
    })
  );

const renderEntrypoint = (
  runtimePlans: RuntimeTargetPlan[],
  requiredSecrets: string[]
): string => {
  const lines = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "require_env() {",
    '  local name=\"$1\"',
    '  if [ -z \"${!name:-}\" ]; then',
    '    echo \"Missing required env: $name\" >&2',
    "    exit 1",
    "  fi",
    "}",
    "",
    "require_file() {",
    '  local target=\"$1\"',
    '  if [ ! -f \"$target\" ]; then',
    '    echo \"Missing required file: $target\" >&2',
    "    exit 1",
    "  fi",
    "}",
    ""
  ];

  for (const secretName of requiredSecrets) {
    lines.push(`require_env ${shellQuote(secretName)}`);
  }

  if (requiredSecrets.length > 0) {
    lines.push("");
  }

  if (runtimePlans.length === 1) {
    const plan = runtimePlans[0]!;
    const commandTokens = resolveStartCommand(plan);
    const envAssignments = createEnvironmentAssignments(plan);

    lines.push(
      `mkdir -p ${shellQuote(plan.instancePaths.workspacePath)}`,
      `require_file ${shellQuote(plan.instancePaths.configPath)}`,
      `${envAssignments.join(" ")} exec ${commandTokens.map(shellQuote).join(" ")}`
    );

    return `${lines.join("\n").trimEnd()}\n`;
  }

  lines.push(
    "PIDS=()",
    "",
    "terminate_children() {",
    '  for pid in "${PIDS[@]:-}"; do',
    '    kill "$pid" 2>/dev/null || true',
    "  done",
    "}",
    "",
    "trap terminate_children INT TERM EXIT",
    ""
  );

  for (const plan of runtimePlans) {
    const commandTokens = resolveStartCommand(plan);
    const envAssignments = createEnvironmentAssignments(plan);

    lines.push(
      `mkdir -p ${shellQuote(plan.instancePaths.workspacePath)}`,
      `require_file ${shellQuote(plan.instancePaths.configPath)}`,
      `${envAssignments.join(" ")} ${commandTokens.map(shellQuote).join(" ")} &`,
      'PIDS+=("$!")',
      ""
    );
  }

  lines.push(
    'if [ "${#PIDS[@]}" -eq 0 ]; then',
    '  echo "No runtime targets were generated for this compile output" >&2',
    "  exit 1",
    "fi",
    "",
    "status=0",
    'for pid in "${PIDS[@]}"; do',
    '  if ! wait "$pid"; then',
    "    status=1",
    "  fi",
    "done",
    "",
    'exit "$status"'
  );

  return `${lines.join("\n").trimEnd()}\n`;
};

export const createContainerArtifacts = async (
  plan: CompilePlan,
  compiledNodes: CompiledNodeArtifact[]
): Promise<GeneratedContainerArtifacts> => {
  const runtimePlans = await createRuntimeTargetPlans(plan, compiledNodes);
  const envVariables = [...createEnvVariableMap(compiledNodes, runtimePlans).values()].sort(
    (left, right) => left.name.localeCompare(right.name)
  );
  const requiredSecrets = envVariables
    .filter((variable) => variable.required)
    .map((variable) => variable.name)
    .sort();

  const files: EmittedFile[] = [
    ...createRootfsFiles(runtimePlans),
    {
      content: await renderDockerfile(runtimePlans),
      path: "Dockerfile"
    },
    {
      content: renderEntrypoint(runtimePlans, requiredSecrets),
      path: "entrypoint.sh"
    },
    {
      content: renderEnvExample(envVariables),
      path: ".env.example"
    }
  ];

  const ports = [...new Set(runtimePlans.flatMap((plan) => (plan.port ? [plan.port] : [])))].sort(
    (left, right) => left - right
  );
  const runtimesInstalled = [...new Set(runtimePlans.map((plan) => plan.runtimeName))].sort();

  return {
    executablePaths: ["entrypoint.sh"],
    files,
    report: {
      dockerfile: "Dockerfile",
      entrypoint: "entrypoint.sh",
      env_example: ".env.example",
      ports,
      runtimes_installed: runtimesInstalled,
      secrets_required: requiredSecrets
    }
  };
};
