import path from "node:path";

import { createRuntimeInstallRecipe } from "../runtime/index.js";
import type { EmittedFile } from "../runtime/index.js";
import { SpawnfileError } from "../shared/index.js";

import type {
  ContainerEnvVariable,
  RuntimeTargetPlan
} from "./containerArtifactsTypes.js";

const CONTAINER_ROOTFS_ROOT = "container/rootfs";
const GATEWAY_PORT_PLACEHOLDER = "<gateway-port>";
const WORKSPACE_PLACEHOLDER = "<workspace-path>";

const shellQuote = (value: string): string => `'${value.replace(/'/g, `'\"'\"'`)}'`;

const extractNodeMajorVersion = (image: string): number =>
  Number(image.match(/^node:(\d+)/)?.[1] ?? "0");

const createPackageInstallCommand = (packages: string[]): string =>
  `RUN apt-get update && apt-get install -y --no-install-recommends ${packages.join(" ")} && rm -rf /var/lib/apt/lists/*`;

const selectBaseImage = (runtimePlans: RuntimeTargetPlan[]): string => {
  const firstRuntimeMeta = runtimePlans[0]?.meta;

  if (runtimePlans.length <= 1) {
    return firstRuntimeMeta?.standaloneBaseImage ?? "debian:bookworm-slim";
  }

  const nodeBaseImages = runtimePlans
    .map((plan) => plan.meta.standaloneBaseImage)
    .filter((image) => image.startsWith("node:"))
    .sort((left, right) => extractNodeMajorVersion(right) - extractNodeMajorVersion(left));

  return nodeBaseImages[0] ?? "debian:bookworm-slim";
};

export const renderEnvExample = (variables: ContainerEnvVariable[]): string => {
  if (variables.length === 0) {
    return "# No environment variables were detected during compile.\n";
  }

  const lines = ["# Generated by spawnfile compile", ""];
  const requiredVariables = variables.filter((variable) => variable.required);
  const optionalVariables = variables.filter((variable) => !variable.required);

  if (requiredVariables.length > 0) {
    lines.push("# Required");
    for (const variable of requiredVariables) {
      lines.push(`# ${variable.description}`);
      lines.push(`${variable.name}=`);
      lines.push("");
    }
  }

  if (optionalVariables.length > 0) {
    lines.push("# Optional");
    for (const variable of optionalVariables) {
      lines.push(`# ${variable.description}`);
      lines.push(`${variable.name}=`);
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
};

export const renderDockerfile = async (
  runtimePlans: RuntimeTargetPlan[]
): Promise<string> => {
  const runtimeNames = [...new Set(runtimePlans.map((plan) => plan.runtimeName))];
  const runtimeRecipes = await Promise.all(
    runtimeNames.map((runtimeName) => createRuntimeInstallRecipe(runtimeName))
  );
  const baseImage = selectBaseImage(runtimePlans);
  const systemDeps = [
    ...new Set(runtimePlans.flatMap((plan) => plan.meta.systemDeps))
  ].sort();
  const exposedPorts = [...new Set(runtimePlans.flatMap((plan) => (plan.port ? [plan.port] : [])))].sort(
    (left, right) => left - right
  );

  const lines = [`FROM ${baseImage}`, "USER root", "", "WORKDIR /opt/spawnfile"];

  if (systemDeps.length > 0) {
    lines.push(createPackageInstallCommand(systemDeps), "");
  }

  for (const recipe of runtimeRecipes) {
    for (const copyCommand of recipe.copyCommands) {
      lines.push(copyCommand);
    }
    for (const command of recipe.commands) {
      lines.push(`RUN ${command}`);
    }
    lines.push("");
  }

  lines.push(
    "COPY container/rootfs/ /",
    "COPY .env.example /opt/spawnfile/.env.example",
    'COPY entrypoint.sh /opt/spawnfile/entrypoint.sh',
    "RUN chmod +x /opt/spawnfile/entrypoint.sh"
  );

  if (exposedPorts.length > 0) {
    lines.push(`EXPOSE ${exposedPorts.join(" ")}`);
  }

  lines.push('ENTRYPOINT ["/opt/spawnfile/entrypoint.sh"]');
  return `${lines.join("\n").trimEnd()}\n`;
};

const createEnvironmentAssignments = (plan: RuntimeTargetPlan): string[] => {
  const envAssignments: string[] = [];

  if (plan.instancePaths.homePath) {
    envAssignments.push(`HOME=${shellQuote(plan.instancePaths.homePath)}`);
  }

  if (plan.meta.homeEnv && plan.instancePaths.homePath) {
    envAssignments.push(`${plan.meta.homeEnv}=${shellQuote(plan.instancePaths.homePath)}`);
  }

  if (plan.meta.configPathEnv) {
    envAssignments.push(`${plan.meta.configPathEnv}=${shellQuote(plan.instancePaths.configPath)}`);
  }

  if (plan.meta.portEnv && plan.port) {
    envAssignments.push(`${plan.meta.portEnv}=${shellQuote(String(plan.port))}`);
  }

  for (const [name, value] of Object.entries(plan.meta.staticEnv ?? {}).sort(([left], [right]) =>
    left.localeCompare(right)
  )) {
    envAssignments.push(`${name}=${shellQuote(value)}`);
  }

  return envAssignments;
};

const createEnvFileWrites = (plan: RuntimeTargetPlan): string[] =>
  plan.envFiles.map(
    (binding) => `write_env_file ${shellQuote(binding.envName)} ${shellQuote(binding.filePath)}`
  );

const resolveStartCommand = (plan: RuntimeTargetPlan): string[] =>
  plan.meta.startCommand
    .map((token) =>
      token
        .replace("<runtime-root>", plan.runtimeRoot)
        .replace("<port>", plan.port ? String(plan.port) : "")
    )
    .filter((token) => token.length > 0);

export const createRootfsFiles = (runtimePlans: RuntimeTargetPlan[]): EmittedFile[] =>
  runtimePlans.flatMap((plan) =>
    plan.targetFiles.map((file) => {
      if (file.path === plan.meta.configFileName) {
        return {
          content: file.content
            .replaceAll(WORKSPACE_PLACEHOLDER, plan.instancePaths.workspacePath)
            .replaceAll(
              `"${GATEWAY_PORT_PLACEHOLDER}"`,
              plan.port ? String(plan.port) : "0"
            )
            .replaceAll(GATEWAY_PORT_PLACEHOLDER, plan.port ? String(plan.port) : ""),
          path: `${CONTAINER_ROOTFS_ROOT}${plan.instancePaths.configPath}`
        };
      }

      if (file.path.startsWith("workspace/")) {
        const relativeWorkspacePath = file.path.slice("workspace/".length);
        return {
          content: file.content,
          path: `${CONTAINER_ROOTFS_ROOT}${path.posix.join(
            plan.instancePaths.workspacePath,
            relativeWorkspacePath
          )}`
        };
      }

      throw new SpawnfileError(
        "runtime_error",
        `Container target ${plan.id} for ${plan.runtimeName} emitted unsupported path ${file.path}`
      );
    })
  );

export const renderEntrypoint = (
  runtimePlans: RuntimeTargetPlan[],
  requiredSecrets: string[]
): string => {
  const lines = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "require_env() {",
    '  local name=\"$1\"',
    '  if [ -z \"${!name:-}\" ]; then',
    '    echo \"Missing required env: $name\" >&2',
    "    exit 1",
    "  fi",
    "}",
    "",
    "require_file() {",
    '  local target=\"$1\"',
    '  if [ ! -f \"$target\" ]; then',
    '    echo \"Missing required file: $target\" >&2',
    "    exit 1",
    "  fi",
    "}",
    "",
    "write_env_file() {",
    '  local name=\"$1\"',
    '  local target=\"$2\"',
    '  mkdir -p \"$(dirname \"$target\")\"',
    '  printf %s \"${!name}\" > \"$target\"',
    "}",
    ""
  ];

  for (const secretName of requiredSecrets) {
    lines.push(`require_env ${shellQuote(secretName)}`);
  }

  if (requiredSecrets.length > 0) {
    lines.push("");
  }

  if (runtimePlans.length === 1) {
    const plan = runtimePlans[0]!;
    const commandTokens = resolveStartCommand(plan);
    const envAssignments = createEnvironmentAssignments(plan);
    const envFileWrites = createEnvFileWrites(plan);

    lines.push(
      `mkdir -p ${shellQuote(plan.instancePaths.workspacePath)}`,
      `require_file ${shellQuote(plan.instancePaths.configPath)}`,
      ...envFileWrites,
      `${envAssignments.join(" ")} exec ${commandTokens.map(shellQuote).join(" ")}`
    );

    return `${lines.join("\n").trimEnd()}\n`;
  }

  lines.push(
    "PIDS=()",
    "",
    "terminate_children() {",
    '  for pid in "${PIDS[@]:-}"; do',
    '    kill "$pid" 2>/dev/null || true',
    "  done",
    "}",
    "",
    "trap terminate_children INT TERM EXIT",
    ""
  );

  for (const plan of runtimePlans) {
    const commandTokens = resolveStartCommand(plan);
    const envAssignments = createEnvironmentAssignments(plan);
    const envFileWrites = createEnvFileWrites(plan);

    lines.push(
      `mkdir -p ${shellQuote(plan.instancePaths.workspacePath)}`,
      `require_file ${shellQuote(plan.instancePaths.configPath)}`,
      ...envFileWrites,
      `${envAssignments.join(" ")} ${commandTokens.map(shellQuote).join(" ")} &`,
      'PIDS+=("$!")',
      ""
    );
  }

  lines.push(
    'if [ "${#PIDS[@]}" -eq 0 ]; then',
    '  echo "No runtime targets were generated for this compile output" >&2',
    "  exit 1",
    "fi",
    "",
    "status=0",
    'for pid in "${PIDS[@]}"; do',
    '  if ! wait "$pid"; then',
    "    status=1",
    "  fi",
    "done",
    "",
    'exit "$status"'
  );

  return `${lines.join("\n").trimEnd()}\n`;
};
