import path from "node:path";

import {
  DISTRIBUTION_REPORT_IMAGE_PATH,
  WORLD_BINDINGS_IMAGE_PATH
} from "../distribution/index.js";
import { createRuntimeInstallRecipe } from "../runtime/index.js";
import type {
  EmittedFile,
  RuntimeContainerPackageOverrides,
  RuntimeInstallRecipe
} from "../runtime/index.js";
import { SpawnfileError } from "../shared/index.js";

import type {
  ContainerEnvVariable,
  RuntimeTargetPlan
} from "./containerArtifactsTypes.js";
import type { EntrypointOptions } from "./containerEntrypointRender.js";
export { renderEntrypoint } from "./containerEntrypointRender.js";
export type { EntrypointOptions } from "./containerEntrypointRender.js";
import {
  DAIMON_RUNTIME_UID,
  DAIMON_UID_ENTRYPOINT_PATH,
  renderDaimonUidEntrypoint
} from "./containerDaimonUidEntrypointRender.js";
import { createStateOwnershipCommand } from "./containerStateOwnershipRender.js";
import {
  RUNTIME_LINK_MATERIALIZER_PATH,
  renderRuntimeLinkMaterializer
} from "./containerRuntimeLinkMaterializer.js";
import { MOLTNET_BIN_DIRECTORY, MOLTNET_BINARY_NAMES } from "./moltnetBinaries.js";
import {
  collectPackagesByManager,
  createAptPackageInstallItem,
  createNpmPackageInstallCommand,
  createNpmPackageInstallItem,
  createPackageInstallCommand,
  createPipxPackageInstallCommand,
  createPipxPackageInstallItem,
  getNpmInstallItemName
} from "./containerPackageRender.js";

const CONTAINER_ROOTFS_ROOT = "container/rootfs";
const GATEWAY_PORT_PLACEHOLDER = "<gateway-port>";
const WORKSPACE_PLACEHOLDER = "<workspace-path>";
const RUNTIME_ROOT_PLACEHOLDER = "<runtime-root>";
const PREBUILT_FINAL_SYSTEM_DEPS_BY_RUNTIME: Readonly<Record<string, ReadonlySet<string>>> = {
  daimon: new Set(["bubblewrap", "dbus-daemon", "gnome-keyring", "util-linux"])
};

const shellQuote = (value: string): string => `'${value.replace(/'/g, `'\"'\"'`)}'`;

const extractNodeMajorVersion = (image: string): number =>
  Number(image.match(/^node:(\d+)/)?.[1] ?? "0");

const selectBaseImage = (
  runtimePlans: RuntimeTargetPlan[],
  runtimeRecipes: RuntimeInstallRecipe[]
): string => {
  const recipeBaseImages = [
    ...new Set(runtimeRecipes.flatMap((recipe) => recipe.baseImage ? [recipe.baseImage] : []))
  ];
  if (recipeBaseImages.length === 1 && runtimePlans.length === runtimeRecipes.length) {
    return recipeBaseImages[0]!;
  }

  const firstRuntimeMeta = runtimePlans[0]?.meta;

  if (runtimePlans.length <= 1) {
    return firstRuntimeMeta?.standaloneBaseImage ?? "debian:bookworm-slim";
  }

  const nodeBaseImages = runtimePlans
    .map((plan) => plan.meta.standaloneBaseImage)
    .filter((image) => image.startsWith("node:"))
    .sort((left, right) => extractNodeMajorVersion(right) - extractNodeMajorVersion(left));

  return nodeBaseImages[0] ?? "debian:bookworm-slim";
};

export const renderEnvExample = (variables: ContainerEnvVariable[]): string => {
  if (variables.length === 0) {
    return "# No environment variables were detected during compile.\n";
  }

  const lines = ["# Generated by spawnfile compile", ""];
  const requiredVariables = variables.filter((variable) => variable.required);
  const optionalVariables = variables.filter((variable) => !variable.required);

  if (requiredVariables.length > 0) {
    lines.push("# Required");
    for (const variable of requiredVariables) {
      lines.push(`# ${variable.description}`);
      lines.push(`${variable.name}=`);
      lines.push("");
    }
  }

  if (optionalVariables.length > 0) {
    lines.push("# Optional");
    for (const variable of optionalVariables) {
      lines.push(`# ${variable.description}`);
      lines.push(`${variable.name}=`);
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
};

export interface DockerfileDistributionOptions {
  labels: Record<string, string>;
  reportOutputFile: string;
  worldBindingsOutputFile?: string;
}

export const renderDockerfile = async (
  runtimePlans: RuntimeTargetPlan[],
  options: EntrypointOptions & {
    distribution?: DockerfileDistributionOptions;
    runtimePackageOverrides?: RuntimeContainerPackageOverrides;
  } = {}
): Promise<string> => {
  if (options.hasMoltnet && !options.hasStagedMoltnetBinaries) {
    throw new SpawnfileError(
      "compile_error",
      "Moltnet must be supplied as a pinned, digest-verified, pi-bridge-stamped release; unpinned latest installation is disabled"
    );
  }
  const runtimeNames = [...new Set(runtimePlans.map((plan) => plan.runtimeName))];
  const hasDaimon = runtimeNames.includes("daimon");
  const runtimeRecipes = await Promise.all(
    runtimeNames.map((runtimeName) =>
      createRuntimeInstallRecipe(runtimeName, { packageOverrides: options.runtimePackageOverrides })
    )
  );
  const recipeByRuntimeName = new Map(
    runtimeRecipes.map((recipe) => [recipe.runtimeName, recipe])
  );
  const baseImage = selectBaseImage(runtimePlans, runtimeRecipes);
  const needsJsonEnvWriter = runtimePlans.some(
    (plan) => (plan.configEnvBindings?.length ?? 0) > 0
  ) || (options.moltnet?.nodePlans.length ?? 0) > 0
    || (options.moltnet?.serverPlans ?? []).some(
      (plan) => plan.mode === "managed"
        && plan.configPath !== null
        && plan.secretPatches.length > 0
    );
  const needsGit = runtimePlans.some((plan) =>
    (plan.resources ?? []).some((resource) => resource.kind === "git")
  );
  const needsBundle = runtimePlans.some((plan) => (plan.resources ?? []).some((resource) => resource.kind === "bundle"));
  const systemDeps = [
    ...new Set([
      ...runtimePlans.flatMap((plan) =>
        recipeByRuntimeName.get(plan.runtimeName)?.baseImage
          ? plan.meta.systemDeps.filter((dependency) =>
              PREBUILT_FINAL_SYSTEM_DEPS_BY_RUNTIME[plan.runtimeName]?.has(dependency)
            )
          : plan.meta.systemDeps
      ),
      ...(needsGit ? ["git"] : []),
      ...(needsBundle ? ["tar"] : []),
      ...(needsJsonEnvWriter ? ["python3"] : [])
    ])
  ].sort();
  const { apt: aptPackages, npm: npmPackages, pipx: pipxPackages } =
    collectPackagesByManager(runtimePlans);
  const aptDependencies = [
    ...systemDeps,
    ...aptPackages.map((pkg) => createAptPackageInstallItem(pkg)),
    ...(pipxPackages.length > 0 ? ["pipx"] : [])
  ];
  const aptInstallPackages = [...new Set(aptDependencies)].sort();
  const projectNpmPackages = npmPackages.map((pkg) => createNpmPackageInstallItem(pkg));
  const projectNpmPackageNames = new Set(projectNpmPackages.map(getNpmInstallItemName));
  const runtimeNpmPackages = runtimePlans
    .flatMap((plan) => plan.meta.globalNpmPackages ?? [])
    .filter((pkg) => !projectNpmPackageNames.has(getNpmInstallItemName(pkg)));
  const globalNpmPackages = [
    ...new Set([...runtimeNpmPackages, ...projectNpmPackages])
  ].sort();
  const pipxInstallPackages = [...new Set(pipxPackages.map((pkg) => createPipxPackageInstallItem(pkg)))]
    .sort();
  const runtimePorts = runtimePlans.flatMap((plan) =>
    plan.publishedPort ? [plan.publishedPort] : []
  );
  const moltnetPorts = options.moltnetPublishedPorts ?? [];
  const exposedPorts = [...new Set([...runtimePorts, ...moltnetPorts])].sort(
    (left, right) => left - right
  );

  const lines = [];

  lines.push(`FROM ${baseImage}`);

  lines.push("USER root", "", "WORKDIR /opt/spawnfile");

  if (aptInstallPackages.length > 0) {
    lines.push(createPackageInstallCommand(aptInstallPackages), "");
  }

  if (globalNpmPackages.length > 0) {
    lines.push(createNpmPackageInstallCommand(globalNpmPackages), "");
  }

  if (pipxInstallPackages.length > 0) {
    lines.push(createPipxPackageInstallCommand(pipxInstallPackages), "");
  }

  if (options.hasMoltnet && options.hasStagedMoltnetBinaries) {
    lines.push(
      `COPY ${MOLTNET_BIN_DIRECTORY}/ /usr/local/bin/`,
      `RUN chmod +x ${MOLTNET_BINARY_NAMES.map((binaryName) => `/usr/local/bin/${binaryName}`).join(" ")}`,
      ""
    );
  }

  if (options.hasWorkspaceBundles) lines.push("COPY container/workspace-bundles/ /opt/spawnfile/workspace-bundles/", "");

  for (const recipe of runtimeRecipes) {
    for (const copyCommand of recipe.copyCommands) {
      lines.push(copyCommand);
    }
    for (const command of recipe.commands) {
      lines.push(`RUN ${command}`);
    }
    lines.push("");
  }

  lines.push(
    hasDaimon
      ? `RUN if ! getent group spawnfile >/dev/null 2>&1; then groupadd --gid ${DAIMON_RUNTIME_UID} spawnfile; fi && if ! id -u spawnfile >/dev/null 2>&1; then useradd --uid ${DAIMON_RUNTIME_UID} --gid spawnfile --create-home --home-dir /home/spawnfile --shell /bin/bash spawnfile; fi`
      : 'RUN if ! id -u spawnfile >/dev/null 2>&1; then useradd --create-home --home-dir /home/spawnfile --shell /bin/bash spawnfile; fi',
    ""
  );

  lines.push(
    "COPY container/rootfs/ /",
    "COPY .env.example /opt/spawnfile/.env.example",
    'COPY entrypoint.sh /opt/spawnfile/entrypoint.sh',
    `RUN chmod +x /opt/spawnfile/entrypoint.sh${hasDaimon ? ` ${DAIMON_UID_ENTRYPOINT_PATH}` : ""}${hasDaimon ? " && chmod 711 /opt /opt/spawnfile" : ""}`
  );

  if (hasDaimon) {
    for (const runtimeRoot of [...new Set(runtimePlans
      .filter((plan) => plan.runtimeName === "daimon")
      .map((plan) => plan.runtimeRoot))].sort()) {
      lines.push(
        `RUN node ${shellQuote(RUNTIME_LINK_MATERIALIZER_PATH)} ${shellQuote(runtimeRoot)} && rm ${shellQuote(RUNTIME_LINK_MATERIALIZER_PATH)} && test -d ${shellQuote(runtimeRoot)} && test ! -L ${shellQuote(runtimeRoot)} && test -z "$(find -P ${shellQuote(runtimeRoot)} \\( -type l -o ! -user root -o ! -group root \\) -print -quit)" && chmod 711 /opt/spawnfile/runtime-installs ${shellQuote(runtimeRoot)} && find -P ${shellQuote(runtimeRoot)} -type d -exec chmod 711 {} + && find -P ${shellQuote(runtimeRoot)} -type f -perm /111 -exec chmod 555 {} + && find -P ${shellQuote(runtimeRoot)} -type f ! -perm /111 -exec chmod 444 {} + && chmod 555 ${shellQuote(path.posix.join(runtimeRoot, "daimon-start.sh"))}`
      );
    }
  }

  const postRootfsCommands = [
    ...new Set(runtimePlans.flatMap((plan) => plan.meta.postRootfsCommands ?? []))
  ];
  for (const command of postRootfsCommands) {
    lines.push(`RUN ${command}`);
  }

  if (options.distribution) {
    lines.push(
      "",
      `COPY ${options.distribution.reportOutputFile} ${DISTRIBUTION_REPORT_IMAGE_PATH}`,
      ...(options.distribution.worldBindingsOutputFile
        ? [
          `COPY ${options.distribution.worldBindingsOutputFile} ${WORLD_BINDINGS_IMAGE_PATH}`,
          `RUN chmod 600 ${WORLD_BINDINGS_IMAGE_PATH} && chown spawnfile:spawnfile ${WORLD_BINDINGS_IMAGE_PATH}`
        ]
        : []),
      ...Object.entries(options.distribution.labels)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([name, value]) => `LABEL ${name}=${shellQuote(value)}`)
    );
  }

  lines.push(`RUN ${createStateOwnershipCommand(
    runtimePlans,
    options.persistentMountPaths,
    options.moltnet
  )}`);

  if (exposedPorts.length > 0) {
    lines.push(`EXPOSE ${exposedPorts.join(" ")}`);
  }

  if (hasDaimon) {
    const daimonConfig = runtimePlans.find((plan) => plan.runtimeName === "daimon")?.instancePaths.configPath;
    if (!daimonConfig) throw new Error("Daimon container plan is missing its runtime config path");
    const healthProgram = "const fs=require('node:fs');const c=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));fetch(`http://127.0.0.1:${c.host.port}/healthz`).then(async r=>{if(!r.ok||JSON.stringify(await r.json())!==JSON.stringify({status:'ok'}))process.exit(1)}).catch(()=>process.exit(1))";
    lines.push(`HEALTHCHECK --interval=5s --timeout=3s --start-period=10s --retries=12 CMD ["node","-e",${JSON.stringify(healthProgram)},${JSON.stringify(daimonConfig)}]`);
  }

  lines.push(hasDaimon ? "USER root" : "USER spawnfile");
  lines.push(hasDaimon
    ? `ENTRYPOINT ["${DAIMON_UID_ENTRYPOINT_PATH}"]`
    : 'ENTRYPOINT ["/opt/spawnfile/entrypoint.sh"]');
  return `${lines.join("\n").trimEnd()}\n`;
};

export const createRootfsFiles = (
  runtimePlans: RuntimeTargetPlan[],
  persistentMountPaths: string[] = [],
  moltnet?: EntrypointOptions["moltnet"]
): EmittedFile[] => {
  const files = runtimePlans.flatMap((plan) =>
    plan.targetFiles.map((file) => {
      const renderedContent = file.content
        .replaceAll("<config-path>", plan.instancePaths.configPath)
        .replaceAll(WORKSPACE_PLACEHOLDER, plan.instancePaths.workspacePath)
        .replaceAll("<instance-root>", plan.instancePaths.instanceRoot ?? "")
        .replaceAll(RUNTIME_ROOT_PLACEHOLDER, plan.runtimeRoot)
        .replaceAll(
          `"${GATEWAY_PORT_PLACEHOLDER}"`,
          plan.port ? String(plan.port) : "0"
        )
        .replaceAll(GATEWAY_PORT_PLACEHOLDER, plan.port ? String(plan.port) : "");
      if (file.path === plan.meta.configFileName) {
        return {
          content: renderedContent,
          path: `${CONTAINER_ROOTFS_ROOT}${plan.instancePaths.configPath}`
        };
      }

      if (file.path.startsWith("runtime/")) {
        const relativeRuntimePath = file.path.slice("runtime/".length);
        return {
          content: renderedContent,
          path: `${CONTAINER_ROOTFS_ROOT}${path.posix.join(
            plan.runtimeRoot,
            relativeRuntimePath
          )}`
        };
      }

      if (file.path.startsWith("workspace/")) {
        const relativeWorkspacePath = file.path.slice("workspace/".length);
        return {
          content: file.content,
          path: `${CONTAINER_ROOTFS_ROOT}${path.posix.join(
            plan.instancePaths.workspacePath,
            relativeWorkspacePath
          )}`
        };
      }

      if (file.path.startsWith("home/")) {
        if (!plan.instancePaths.homePath) {
          throw new SpawnfileError(
            "runtime_error",
            `Container target ${plan.id} for ${plan.runtimeName} emitted home-scoped files without a home path`
          );
        }

        const relativeHomePath = file.path.slice("home/".length);
        return {
          content: file.content,
          path: `${CONTAINER_ROOTFS_ROOT}${path.posix.join(
            plan.instancePaths.homePath,
            relativeHomePath
          )}`
        };
      }

      throw new SpawnfileError(
        "runtime_error",
        `Container target ${plan.id} for ${plan.runtimeName} emitted unsupported path ${file.path}`
      );
    })
  );
  return runtimePlans.some((plan) => plan.runtimeName === "daimon")
    ? [{
        content: renderRuntimeLinkMaterializer(),
        mode: 0o600,
        path: `${CONTAINER_ROOTFS_ROOT}${RUNTIME_LINK_MATERIALIZER_PATH}`
      }, {
        content: renderDaimonUidEntrypoint(runtimePlans, persistentMountPaths, moltnet),
        mode: 0o755,
        path: `${CONTAINER_ROOTFS_ROOT}${DAIMON_UID_ENTRYPOINT_PATH}`
      }, ...files]
    : files;
};
