import path from "node:path";
import type { RuntimeTargetPlan } from "./containerArtifactsTypes.js";
import { VOLUME_BOOTSTRAP_MARKER, VOLUME_BOOTSTRAP_MARKER_CONTENT } from "./containerVolumeBootstrap.js";
const SPAWNFILE_PRIVATE_STATE_ROOT = "/var/lib/spawnfile";
export const renderDaimonOwnershipProgram = (
  opaqueTargets: string[],
  opaqueDescendantRoots: string[],
  immutableRuntimeRoots: string[],
  volumeIdentityFiles: Array<{ path: string; identity: string }>,
  privateDirectories: string[],
  privateFiles: string[],
  privateModeDirectories: string[],
  creatablePrivateDirectories: Array<{ anchor: string; target: string }>
): string => [
  "const fs = require('node:fs');",
  "const constants = fs.constants;",
  "const uid = Number(process.argv[2]);",
  "const roots = process.argv.slice(3);",
  "const fail = (message) => { process.stderr.write(`Daimon ownership guard: ${message}\\n`); process.exit(1); };",
  `const opaquePaths = new Set(${JSON.stringify(opaqueTargets)});`,
  `const opaqueDescendantRoots = new Set(${JSON.stringify(opaqueDescendantRoots)});`,
  `const immutableRuntimeRoots = ${JSON.stringify(immutableRuntimeRoots)};`,
  `const volumeIdentityFiles = ${JSON.stringify(volumeIdentityFiles)};`,
  "const volumeIdentityPaths = new Set(volumeIdentityFiles.map((entry) => entry.path)); if (volumeIdentityPaths.size !== volumeIdentityFiles.length) fail('duplicate volume identity path');",
  `const privateDirectories = ${JSON.stringify(privateDirectories)};`,
  `const privateFiles = ${JSON.stringify(privateFiles)};`,
  `const privateModeDirectories = ${JSON.stringify(privateModeDirectories)};`,
  `const creatablePrivateDirectories = ${JSON.stringify(creatablePrivateDirectories)};`,
  "if (!Number.isSafeInteger(uid) || uid < 1 || roots.length === 0) fail('invalid compiler-authored roots');",
  "const decodeMountPath = (value) => value.replace(/\\\\([0-7]{3})/g, (_, octal) => String.fromCharCode(Number.parseInt(octal, 8)));",
  "const mountOptionsFor = (target) => {",
  "  const matches = fs.readFileSync('/proc/self/mountinfo', 'utf8').trim().split('\\n').map((line) => line.split(' ')).filter((parts) => parts.length > 5).map((parts) => ({ point: decodeMountPath(parts[4]), options: parts[5].split(',') })).filter((mount) => target === mount.point || target.startsWith(`${mount.point}/`));",
  "  return matches.sort((left, right) => right.point.length - left.point.length)[0]?.options ?? [];",
  "};",
  "const openDirectoryPath = (target) => {",
  "  if (!target.startsWith('/') || target === '/' || target.includes('//') || target.split('/').includes('..')) fail('unsafe compiler-authored root');",
  "  let fd = fs.openSync('/', constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW);",
  "  try {",
  "    for (const segment of target.slice(1).split('/')) {",
  "      if (!segment || segment === '.' || segment === '..') fail('unsafe compiler-authored root');",
  "      const next = fs.openSync(`/proc/self/fd/${fd}/${segment}`, constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW);",
  "      fs.closeSync(fd); fd = next;",
  "    }",
  "    const info = fs.fstatSync(fd);",
  "    if (!info.isDirectory()) fail('root is not a directory');",
  "    if (mountOptionsFor(target).includes('ro')) fail('root is read-only');",
  "    return fd;",
  "  } catch (error) { try { fs.closeSync(fd); } catch {} fail('root has a symbolic-link or unavailable path component'); }",
  "};",
  "const openRegularFilePath = (target) => {",
  "  if (!target.startsWith('/') || target === '/' || target.includes('//') || target.split('/').includes('..')) fail('unsafe compiler-authored file');",
  "  let fd = fs.openSync('/', constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW);",
  "  try {",
  "    const segments = target.slice(1).split('/');",
  "    for (const [index, segment] of segments.entries()) {",
  "      if (!segment || segment === '.' || segment === '..') fail('unsafe compiler-authored file');",
  "      const isFile = index === segments.length - 1;",
  "      const next = fs.openSync(`/proc/self/fd/${fd}/${segment}`, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK | (isFile ? 0 : constants.O_DIRECTORY));",
  "      fs.closeSync(fd); fd = next;",
  "    }",
  "    const info = fs.fstatSync(fd);",
  "    if (!info.isFile() || info.nlink !== 1) fail('compiler-authored file is not one regular file');",
  "    if (mountOptionsFor(target).includes('ro')) fail('compiler-authored file is read-only');",
  "    return fd;",
  "  } catch (error) { try { fs.closeSync(fd); } catch {} fail('file has a symbolic-link or unavailable path component'); }",
  "};",
  "const secureFixedTraversalAncestor = (target) => {",
  "  const fd = openDirectoryPath(target);",
  "  try {",
  "    const info = fs.fstatSync(fd);",
  "    const mode = info.mode & 0o777;",
  "    if (info.uid !== 0 || info.gid !== 0 || (mode !== 0o775 && mode !== 0o755 && mode !== 0o711)) fail('fixed state ancestor has an unexpected preimage');",
  "    fs.fchmodSync(fd, 0o711);",
  "    const secured = fs.fstatSync(fd);",
  "    if (secured.uid !== 0 || secured.gid !== 0 || (secured.mode & 0o777) !== 0o711) fail('fixed state ancestor traversal mode did not apply');",
  "  } finally { fs.closeSync(fd); }",
  "};",
  "const secureSharedStateAncestor = (target) => {",
  "  const fd = openDirectoryPath(target);",
  "  try {",
  "    const info = fs.fstatSync(fd);",
  "    const mode = info.mode & 0o777;",
  "    const current = info.uid === 0 && info.gid === 0 && mode === 0o711;",
  "    const legacy = info.uid === uid && info.gid === uid && mode === 0o700;",
  "    if (!current && !legacy) fail('shared state ancestor has an unexpected preimage');",
  "    fs.fchownSync(fd, 0, 0); fs.fchmodSync(fd, 0o711);",
  "    const secured = fs.fstatSync(fd);",
  "    if (secured.uid !== 0 || secured.gid !== 0 || (secured.mode & 0o777) !== 0o711) fail('shared state ancestor traversal mode did not apply');",
  "  } finally { fs.closeSync(fd); }",
  "};",
  "const createPrivateDirectoryPath = ({ anchor, target }) => {",
  "  if (target !== anchor && !target.startsWith(`${anchor}/`)) fail('private directory escapes its compiler-authored anchor');",
  "  let fd = openDirectoryPath(anchor);",
  "  const anchorInfo = fs.fstatSync(fd);",
  "  const createdFds = [];",
  "  let preparationError;",
  "  let current = anchor;",
  "  try {",
  "    const relative = target.slice(anchor.length).replace(/^\\//, '');",
  "    for (const segment of relative ? relative.split('/') : []) {",
  "      if (!segment || segment === '.' || segment === '..') throw new Error('unsafe');",
  "      fs.fchownSync(fd, 0, 0);",
  "      const childPath = `/proc/self/fd/${fd}/${segment}`;",
  "      try { fs.mkdirSync(childPath, { mode: 0o700 }); } catch (error) { if (error.code !== 'EEXIST') throw error; }",
  "      const next = fs.openSync(childPath, constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW);",
  "      createdFds.push(fd); fd = next; current = `${current}/${segment}`;",
  "      const info = fs.fstatSync(fd);",
  "      if (!info.isDirectory() || mountOptionsFor(current).includes('ro')) throw new Error('unsafe-or-read-only');",
  "    }",
  "    createdFds.push(fd); fd = -1;",
  "    for (const ownedFd of createdFds.slice(1).reverse()) { fs.fchownSync(ownedFd, 0, 0); fs.fchmodSync(ownedFd, 0o700); fs.fchownSync(ownedFd, uid, uid); }",
  "  } catch (error) { preparationError = error.code ?? error.message ?? 'unknown'; } finally { const anchorFd = createdFds[0] ?? fd; if (anchorFd >= 0) try { fs.fchownSync(anchorFd, anchorInfo.uid, anchorInfo.gid); } catch { preparationError = 'restore-anchor-ownership'; }; if (fd >= 0) try { fs.closeSync(fd); } catch {}; for (const ownedFd of createdFds) try { fs.closeSync(ownedFd); } catch {} }",
  "  if (preparationError) fail(`unable to prepare compiler-authored private directory: ${preparationError}`);",
  "};",
  "const ownTree = (fd, device, currentPath) => {",
  "  const info = fs.fstatSync(fd);",
  "  if (!info.isDirectory() || info.dev !== device) return;",
  "  fs.fchownSync(fd, uid, uid);",
  "  for (const entry of fs.readdirSync(`/proc/self/fd/${fd}`, { withFileTypes: true })) {",
  "    const childPath = `${currentPath}/${entry.name}`;",
  "    if (opaquePaths.has(childPath) || opaqueDescendantRoots.has(childPath) || volumeIdentityPaths.has(childPath)) continue;",
  "    let child;",
  "    try { child = fs.openSync(`/proc/self/fd/${fd}/${entry.name}`, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK | (entry.isDirectory() ? constants.O_DIRECTORY : 0)); } catch { fail('state tree contains a symbolic link or unavailable entry'); }",
  "    try { const childInfo = fs.fstatSync(child); if (childInfo.dev !== device || mountOptionsFor(childPath).includes('ro')) continue; if (childInfo.isDirectory()) ownTree(child, device, childPath); else if (childInfo.isFile() && childInfo.nlink === 1) fs.fchownSync(child, uid, uid); else if (!childInfo.isFile()) fail('state tree contains an unsupported entry'); } finally { fs.closeSync(child); }",
  "  }",
  "};",
  "const validateImmutableTree = (fd, device, currentPath) => {",
  "  const info = fs.fstatSync(fd);",
  "  if (!info.isDirectory() || info.dev !== device || info.uid !== 0 || info.gid !== 0 || (info.mode & 0o777) !== 0o711) fail('immutable runtime directory is unsafe');",
  "  for (const entry of fs.readdirSync(`/proc/self/fd/${fd}`, { withFileTypes: true })) {",
  "    let child; try { child = fs.openSync(`/proc/self/fd/${fd}/${entry.name}`, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK | (entry.isDirectory() ? constants.O_DIRECTORY : 0)); } catch { fail('immutable runtime contains a symbolic link or unavailable entry'); }",
  "    try { const childInfo = fs.fstatSync(child); if (childInfo.dev !== device || childInfo.uid !== 0 || childInfo.gid !== 0) fail('immutable runtime entry is unsafe'); if (childInfo.isDirectory()) validateImmutableTree(child, device, `${currentPath}/${entry.name}`); else if (!childInfo.isFile() || childInfo.nlink !== 1 || (childInfo.mode & 0o222) !== 0) fail('immutable runtime contains an unsupported entry'); } finally { fs.closeSync(child); }",
  "  }",
  "};",
  "const securePrivateDirectory = (fd) => {",
  "  try {",
  "    fs.fchownSync(fd, 0, 0);",
  "    fs.fchmodSync(fd, 0o700);",
  "    fs.fchownSync(fd, uid, uid);",
  "  } catch {",
  "    try { fs.fchownSync(fd, uid, uid); } catch {}",
  "    fail('unable to secure private directory');",
  "  }",
  "  const info = fs.fstatSync(fd);",
  "  if (info.uid !== uid || info.gid !== uid || (info.mode & 0o777) !== 0o700) fail('private directory ownership or mode did not apply');",
  "};",
  "const securePrivateFile = (fd) => {",
  "  try {",
  "    fs.fchownSync(fd, 0, 0);",
  "    fs.fchmodSync(fd, 0o600);",
  "    fs.fchownSync(fd, uid, uid);",
  "  } catch {",
  "    try { fs.fchownSync(fd, uid, uid); } catch {}",
  "    fail('unable to secure private file');",
  "  }",
  "  const info = fs.fstatSync(fd);",
  "  if (info.uid !== uid || info.gid !== uid || (info.mode & 0o777) !== 0o600) fail('private file ownership or mode did not apply');",
  "};",
  `const volumeBootstrapMarker = ${JSON.stringify(VOLUME_BOOTSTRAP_MARKER)}, volumeBootstrapContent = ${JSON.stringify(`${VOLUME_BOOTSTRAP_MARKER_CONTENT}\n`)};`,
  "const verifyVolumeIdentityFile = (fd, expected, mode, device) => { const before = fs.fstatSync(fd); if (!before.isFile() || before.nlink !== 1 || before.uid !== 0 || before.gid !== 0 || (before.mode & 0o777) !== mode || before.dev !== device || before.size !== Buffer.byteLength(expected)) fail('volume identity anchor is unsafe'); const bytes = Buffer.alloc(before.size); let offset=0; while(offset<bytes.length){const count=fs.readSync(fd,bytes,offset,bytes.length-offset,offset);if(count<1)fail('volume identity anchor read failed');offset+=count;} const after = fs.fstatSync(fd); if (!bytes.equals(Buffer.from(expected)) || after.dev !== before.dev || after.ino !== before.ino || after.size !== before.size || after.mtimeMs !== before.mtimeMs || after.ctimeMs !== before.ctimeMs) fail('volume identity anchor changed'); };",
  "const secureVolumeIdentity = (entry) => { const parentPath = require('node:path').posix.dirname(entry.path); if (entry.path !== `${parentPath}/.spawnfile-resource-identity`) fail('volume identity anchor path is invalid'); const parent = openDirectoryPath(parentPath); let marker, sentinel; try { const parentInfo = fs.fstatSync(parent), parentMode = parentInfo.mode & 0o777, freshParent = parentInfo.uid === 0 && parentInfo.gid === 0 && parentMode === 0o755, establishedParent = parentInfo.uid === uid && parentInfo.gid === uid && parentMode === 0o755; if (!freshParent && !establishedParent) fail('volume identity parent is unsafe'); const names = fs.readdirSync(`/proc/self/fd/${parent}`).sort(), hasSentinel = names.includes('.spawnfile-resource-identity'), hasMarker = names.includes(volumeBootstrapMarker); if (hasSentinel) { sentinel = fs.openSync(`/proc/self/fd/${parent}/.spawnfile-resource-identity`, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK); verifyVolumeIdentityFile(sentinel, `${entry.identity}\n`, 0o644, parentInfo.dev); if (hasMarker) { if (!freshParent || names.length !== 2) fail('volume bootstrap recovery preimage is unsafe'); marker = fs.openSync(`/proc/self/fd/${parent}/${volumeBootstrapMarker}`, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK); verifyVolumeIdentityFile(marker, volumeBootstrapContent, 0o600, parentInfo.dev); fs.fsyncSync(sentinel); fs.fsyncSync(parent); verifyVolumeIdentityFile(sentinel, `${entry.identity}\n`, 0o644, parentInfo.dev); verifyVolumeIdentityFile(marker, volumeBootstrapContent, 0o600, parentInfo.dev); fs.unlinkSync(`/proc/self/fd/${parent}/${volumeBootstrapMarker}`); fs.fsyncSync(parent); } return; } if (!freshParent || names.length !== 1 || !hasMarker) fail('volume bootstrap preimage is unsafe'); marker = fs.openSync(`/proc/self/fd/${parent}/${volumeBootstrapMarker}`, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK); verifyVolumeIdentityFile(marker, volumeBootstrapContent, 0o600, parentInfo.dev); const expected = Buffer.from(`${entry.identity}\n`); try { sentinel = fs.openSync(`/proc/self/fd/${parent}/.spawnfile-resource-identity`, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW | constants.O_NONBLOCK, 0o644); let offset=0; while(offset<expected.length){const written=fs.writeSync(sentinel,expected,offset,expected.length-offset,offset);if(written<1)fail('volume identity anchor write failed');offset+=written;} fs.fchownSync(sentinel,0,0);fs.fchmodSync(sentinel,0o644);fs.fsyncSync(sentinel); } finally { expected.fill(0); } fs.closeSync(sentinel); sentinel=undefined; sentinel=fs.openSync(`/proc/self/fd/${parent}/.spawnfile-resource-identity`,constants.O_RDONLY|constants.O_NOFOLLOW|constants.O_NONBLOCK);verifyVolumeIdentityFile(sentinel,`${entry.identity}\n`,0o644,parentInfo.dev);fs.fsyncSync(parent);verifyVolumeIdentityFile(marker,volumeBootstrapContent,0o600,parentInfo.dev);fs.unlinkSync(`/proc/self/fd/${parent}/${volumeBootstrapMarker}`);fs.fsyncSync(parent); } finally { if(marker!==undefined)fs.closeSync(marker);if(sentinel!==undefined)fs.closeSync(sentinel);fs.closeSync(parent); } };",
  "for (const target of ['/var', '/var/lib']) secureFixedTraversalAncestor(target);",
  `secureSharedStateAncestor('${SPAWNFILE_PRIVATE_STATE_ROOT}');`,
  "for (const target of immutableRuntimeRoots) { const fd = openDirectoryPath(target); try { validateImmutableTree(fd, fs.fstatSync(fd).dev, target); const start = openRegularFilePath(`${target}/daimon-start.sh`); try { const info = fs.fstatSync(start); if ((info.mode & 0o111) === 0 || (info.mode & 0o222) !== 0 || info.uid !== 0 || info.gid !== 0) fail('Daimon start script is not immutable executable'); } finally { fs.closeSync(start); } } finally { fs.closeSync(fd); } }",
  "for (const entry of volumeIdentityFiles) secureVolumeIdentity(entry);",
  "for (const target of creatablePrivateDirectories) createPrivateDirectoryPath(target);",
  "for (const target of privateDirectories) { if (opaquePaths.has(target)) fail('compiler-authored directory overlaps opaque path'); const fd = openDirectoryPath(target); try { fs.fchownSync(fd, uid, uid); } finally { fs.closeSync(fd); } }",
  "for (const target of privateModeDirectories) { if (opaquePaths.has(target)) fail('private directory overlaps opaque path'); const fd = openDirectoryPath(target); try { securePrivateDirectory(fd); } finally { fs.closeSync(fd); } }",
  "for (const target of privateFiles) { if (opaquePaths.has(target)) fail('compiler-authored file overlaps opaque path'); const fd = openRegularFilePath(target); try { securePrivateFile(fd); } finally { fs.closeSync(fd); } }",
  "for (const root of roots) { if (opaquePaths.has(root) || opaqueDescendantRoots.has(root)) fail('state root overlaps opaque path'); const fd = openDirectoryPath(root); try { ownTree(fd, fs.fstatSync(fd).dev, root); } finally { fs.closeSync(fd); } }"
].join("\n");

export const resolveDaimonVolumeIdentityFiles = (runtimePlans:RuntimeTargetPlan[]):Array<{path:string;identity:string}> => {
  const byPath=new Map<string,string>();
  const resourceRoot="/var/lib/spawnfile/resources";
  for(const resource of runtimePlans.flatMap((plan)=>plan.resources??[])){
    if(resource.kind!=="volume"||!("replacementSentinel" in resource)||typeof resource.replacementSentinel!=="string"||!("resolvedIdentity" in resource)||typeof resource.resolvedIdentity!=="string")continue;
    const relative=typeof resource.backingPath==="string"?path.posix.relative(resourceRoot,resource.backingPath):"";
    if(typeof resource.backingPath!=="string"||path.posix.normalize(resource.backingPath)!==resource.backingPath||resource.backingPath.includes("//")||!relative||relative.startsWith("../")||path.posix.isAbsolute(relative)||resource.replacementSentinel!==path.posix.join(resource.backingPath,".spawnfile-resource-identity")||!/^sha256:[a-f0-9]{64}$/u.test(resource.resolvedIdentity))throw new Error("invalid compiler-authored volume identity anchor");
    const existing=byPath.get(resource.replacementSentinel);if(existing!==undefined&&existing!==resource.resolvedIdentity)throw new Error("conflicting compiler-authored volume identity anchor");byPath.set(resource.replacementSentinel,resource.resolvedIdentity);
  }
  return [...byPath].map(([path,identity])=>({path,identity})).sort((left,right)=>left.path.localeCompare(right.path));
};
