import path from "node:path";

import { DISTRIBUTION_REPORT_IMAGE_PATH } from "../distribution/index.js";
import { createRuntimeInstallRecipe } from "../runtime/index.js";
import type { EmittedFile, RuntimeInstallRecipe } from "../runtime/index.js";
import { SpawnfileError } from "../shared/index.js";

import type {
  ContainerEnvVariable,
  RuntimeTargetPlan
} from "./containerArtifactsTypes.js";
import type { EntrypointOptions } from "./containerEntrypointRender.js";
export { renderEntrypoint } from "./containerEntrypointRender.js";
export type { EntrypointOptions } from "./containerEntrypointRender.js";
import { MOLTNET_BIN_DIRECTORY, MOLTNET_BINARY_NAMES } from "./moltnetBinaries.js";
import {
  collectPackagesByManager,
  createAptPackageInstallItem,
  createNpmPackageInstallCommand,
  createNpmPackageInstallItem,
  createPackageInstallCommand,
  createPipxPackageInstallCommand,
  createPipxPackageInstallItem,
  getNpmInstallItemName
} from "./containerPackageRender.js";

const CONTAINER_ROOTFS_ROOT = "container/rootfs";
const GATEWAY_PORT_PLACEHOLDER = "<gateway-port>";
const MOLTNET_INSTALL_SCRIPT_URL = "https://moltnet.dev/install.sh";
const MOLTNET_RELEASE_METADATA_URL = "https://api.github.com/repos/noopolis/moltnet/releases/latest";
const WORKSPACE_PLACEHOLDER = "<workspace-path>";
const RUNTIME_ROOT_PLACEHOLDER = "<runtime-root>";

const shellQuote = (value: string): string => `'${value.replace(/'/g, `'\"'\"'`)}'`;

const extractNodeMajorVersion = (image: string): number =>
  Number(image.match(/^node:(\d+)/)?.[1] ?? "0");

const createStateOwnershipCommand = (persistentMountPaths: string[] = []): string => {
  const mountPaths = [...new Set(persistentMountPaths)].sort();
  const mkdirPaths = [...new Set(["/var/lib/spawnfile", ...mountPaths])].sort();
  const markerCommands = mountPaths.map((mountPath) =>
    `touch ${shellQuote(path.posix.join(mountPath, ".spawnfile-volume-init"))}`
  );
  const chownPaths = [
    ...new Set([
      "/var/lib/spawnfile",
      ...mountPaths.filter((mountPath) => !mountPath.startsWith("/var/lib/spawnfile/"))
    ])
  ].sort();

  return [
    `mkdir -p ${mkdirPaths.map(shellQuote).join(" ")}`,
    ...markerCommands,
    `chown -R spawnfile:spawnfile ${chownPaths.map(shellQuote).join(" ")}`
  ].join(" && ");
};

const selectBaseImage = (
  runtimePlans: RuntimeTargetPlan[],
  runtimeRecipes: RuntimeInstallRecipe[]
): string => {
  const recipeBaseImages = [
    ...new Set(runtimeRecipes.flatMap((recipe) => recipe.baseImage ? [recipe.baseImage] : []))
  ];
  if (recipeBaseImages.length === 1 && runtimePlans.length === runtimeRecipes.length) {
    return recipeBaseImages[0]!;
  }

  const firstRuntimeMeta = runtimePlans[0]?.meta;

  if (runtimePlans.length <= 1) {
    return firstRuntimeMeta?.standaloneBaseImage ?? "debian:bookworm-slim";
  }

  const nodeBaseImages = runtimePlans
    .map((plan) => plan.meta.standaloneBaseImage)
    .filter((image) => image.startsWith("node:"))
    .sort((left, right) => extractNodeMajorVersion(right) - extractNodeMajorVersion(left));

  return nodeBaseImages[0] ?? "debian:bookworm-slim";
};

export const renderEnvExample = (variables: ContainerEnvVariable[]): string => {
  if (variables.length === 0) {
    return "# No environment variables were detected during compile.\n";
  }

  const lines = ["# Generated by spawnfile compile", ""];
  const requiredVariables = variables.filter((variable) => variable.required);
  const optionalVariables = variables.filter((variable) => !variable.required);

  if (requiredVariables.length > 0) {
    lines.push("# Required");
    for (const variable of requiredVariables) {
      lines.push(`# ${variable.description}`);
      lines.push(`${variable.name}=`);
      lines.push("");
    }
  }

  if (optionalVariables.length > 0) {
    lines.push("# Optional");
    for (const variable of optionalVariables) {
      lines.push(`# ${variable.description}`);
      lines.push(`${variable.name}=`);
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
};

export interface DockerfileDistributionOptions {
  labels: Record<string, string>;
  reportOutputFile: string;
}

export const renderDockerfile = async (
  runtimePlans: RuntimeTargetPlan[],
  options: EntrypointOptions & { distribution?: DockerfileDistributionOptions } = {}
): Promise<string> => {
  const runtimeNames = [...new Set(runtimePlans.map((plan) => plan.runtimeName))];
  const runtimeRecipes = await Promise.all(
    runtimeNames.map((runtimeName) => createRuntimeInstallRecipe(runtimeName))
  );
  const recipeByRuntimeName = new Map(
    runtimeRecipes.map((recipe) => [recipe.runtimeName, recipe])
  );
  const baseImage = selectBaseImage(runtimePlans, runtimeRecipes);
  const needsJsonEnvWriter = runtimePlans.some(
    (plan) => (plan.configEnvBindings?.length ?? 0) > 0
  );
  const needsGit = runtimePlans.some((plan) =>
    (plan.resources ?? []).some((resource) => resource.kind === "git")
  );
  const systemDeps = [
    ...new Set([
      ...runtimePlans.flatMap((plan) =>
        recipeByRuntimeName.get(plan.runtimeName)?.baseImage ? [] : plan.meta.systemDeps
      ),
      ...(needsGit ? ["git"] : []),
      ...(options.hasMoltnet && !options.hasStagedMoltnetBinaries
        ? ["ca-certificates", "curl", "tar"]
        : []),
      ...(needsJsonEnvWriter ? ["python3"] : [])
    ])
  ].sort();
  const { apt: aptPackages, npm: npmPackages, pipx: pipxPackages } =
    collectPackagesByManager(runtimePlans);
  const aptDependencies = [
    ...systemDeps,
    ...aptPackages.map((pkg) => createAptPackageInstallItem(pkg)),
    ...(pipxPackages.length > 0 ? ["pipx"] : [])
  ];
  const aptInstallPackages = [...new Set(aptDependencies)].sort();
  const projectNpmPackages = npmPackages.map((pkg) => createNpmPackageInstallItem(pkg));
  const projectNpmPackageNames = new Set(projectNpmPackages.map(getNpmInstallItemName));
  const runtimeNpmPackages = runtimePlans
    .flatMap((plan) => plan.meta.globalNpmPackages ?? [])
    .filter((pkg) => !projectNpmPackageNames.has(getNpmInstallItemName(pkg)));
  const globalNpmPackages = [
    ...new Set([...runtimeNpmPackages, ...projectNpmPackages])
  ].sort();
  const pipxInstallPackages = [...new Set(pipxPackages.map((pkg) => createPipxPackageInstallItem(pkg)))]
    .sort();
  const runtimePorts = runtimePlans.flatMap((plan) =>
    plan.publishedPort ? [plan.publishedPort] : []
  );
  const moltnetPorts = options.moltnetPublishedPorts ?? [];
  const exposedPorts = [...new Set([...runtimePorts, ...moltnetPorts])].sort(
    (left, right) => left - right
  );

  const lines = [];

  lines.push(`FROM ${baseImage}`);

  lines.push("USER root", "", "WORKDIR /opt/spawnfile");

  if (aptInstallPackages.length > 0) {
    lines.push(createPackageInstallCommand(aptInstallPackages), "");
  }

  if (globalNpmPackages.length > 0) {
    lines.push(createNpmPackageInstallCommand(globalNpmPackages), "");
  }

  if (pipxInstallPackages.length > 0) {
    lines.push(createPipxPackageInstallCommand(pipxInstallPackages), "");
  }

  if (options.hasMoltnet && options.hasStagedMoltnetBinaries) {
    lines.push(
      `COPY ${MOLTNET_BIN_DIRECTORY}/ /usr/local/bin/`,
      `RUN chmod +x ${MOLTNET_BINARY_NAMES.map((binaryName) => `/usr/local/bin/${binaryName}`).join(" ")}`,
      ""
    );
  } else if (options.hasMoltnet) {
    lines.push(
      `ADD ${MOLTNET_RELEASE_METADATA_URL} /tmp/spawnfile-moltnet-release.json`,
      `RUN MOLTNET_RELEASE="$${"("}sed -n 's/.*\\"tag_name\\": *\\"\\([^\\"]*\\)\\".*/\\1/p' /tmp/spawnfile-moltnet-release.json | head -n 1${")"}" && echo "Installing Moltnet $${"{MOLTNET_RELEASE:-latest}"}" && MOLTNET_INSTALL_DIR=/usr/local/bin sh -c ${shellQuote(`curl -fsSL ${MOLTNET_INSTALL_SCRIPT_URL} | sh`)}`,
      ""
    );
  }

  for (const recipe of runtimeRecipes) {
    for (const copyCommand of recipe.copyCommands) {
      lines.push(copyCommand);
    }
    for (const command of recipe.commands) {
      lines.push(`RUN ${command}`);
    }
    lines.push("");
  }

  lines.push(
    'RUN if ! id -u spawnfile >/dev/null 2>&1; then useradd --create-home --home-dir /home/spawnfile --shell /bin/bash spawnfile; fi',
    ""
  );

  lines.push(
    "COPY container/rootfs/ /",
    "COPY .env.example /opt/spawnfile/.env.example",
    'COPY entrypoint.sh /opt/spawnfile/entrypoint.sh',
    "RUN chmod +x /opt/spawnfile/entrypoint.sh"
  );

  const postRootfsCommands = [
    ...new Set(runtimePlans.flatMap((plan) => plan.meta.postRootfsCommands ?? []))
  ];
  for (const command of postRootfsCommands) {
    lines.push(`RUN ${command}`);
  }

  if (options.distribution) {
    lines.push(
      "",
      `COPY ${options.distribution.reportOutputFile} ${DISTRIBUTION_REPORT_IMAGE_PATH}`,
      ...Object.entries(options.distribution.labels)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([name, value]) => `LABEL ${name}=${shellQuote(value)}`)
    );
  }

  lines.push(`RUN ${createStateOwnershipCommand(options.persistentMountPaths)}`);

  if (exposedPorts.length > 0) {
    lines.push(`EXPOSE ${exposedPorts.join(" ")}`);
  }

  lines.push("USER spawnfile");
  lines.push('ENTRYPOINT ["/opt/spawnfile/entrypoint.sh"]');
  return `${lines.join("\n").trimEnd()}\n`;
};

export const createRootfsFiles = (runtimePlans: RuntimeTargetPlan[]): EmittedFile[] =>
  runtimePlans.flatMap((plan) =>
    plan.targetFiles.map((file) => {
      if (file.path === plan.meta.configFileName) {
        return {
          content: file.content
            .replaceAll(WORKSPACE_PLACEHOLDER, plan.instancePaths.workspacePath)
            .replaceAll(RUNTIME_ROOT_PLACEHOLDER, plan.runtimeRoot)
            .replaceAll(
              `"${GATEWAY_PORT_PLACEHOLDER}"`,
              plan.port ? String(plan.port) : "0"
            )
            .replaceAll(GATEWAY_PORT_PLACEHOLDER, plan.port ? String(plan.port) : ""),
          path: `${CONTAINER_ROOTFS_ROOT}${plan.instancePaths.configPath}`
        };
      }

      if (file.path.startsWith("runtime/")) {
        const relativeRuntimePath = file.path.slice("runtime/".length);
        return {
          content: file.content,
          path: `${CONTAINER_ROOTFS_ROOT}${path.posix.join(
            plan.runtimeRoot,
            relativeRuntimePath
          )}`
        };
      }

      if (file.path.startsWith("workspace/")) {
        const relativeWorkspacePath = file.path.slice("workspace/".length);
        return {
          content: file.content,
          path: `${CONTAINER_ROOTFS_ROOT}${path.posix.join(
            plan.instancePaths.workspacePath,
            relativeWorkspacePath
          )}`
        };
      }

      if (file.path.startsWith("home/")) {
        if (!plan.instancePaths.homePath) {
          throw new SpawnfileError(
            "runtime_error",
            `Container target ${plan.id} for ${plan.runtimeName} emitted home-scoped files without a home path`
          );
        }

        const relativeHomePath = file.path.slice("home/".length);
        return {
          content: file.content,
          path: `${CONTAINER_ROOTFS_ROOT}${path.posix.join(
            plan.instancePaths.homePath,
            relativeHomePath
          )}`
        };
      }

      throw new SpawnfileError(
        "runtime_error",
        `Container target ${plan.id} for ${plan.runtimeName} emitted unsupported path ${file.path}`
      );
    })
  );
