import { describe, expect, it } from "vitest";

import {
  CREDENTIAL_PROVISIONING_REQUEST_VERSION,
  parseCredentialProvisioningRequest,
  parseCredentialProvisioningRequestBytes
} from "./credentialProvisioningRequest.js";
import { TARGET_SECRET_SOURCE_ERROR } from "./targetSecretSourceRecordCommon.js";

const request = () => ({
  credentials: [
    { bytes: 16, env: "AGENT_ALPHA_TOKEN", kind: "generated-token", name: "agent-alpha-token" },
    {
      content: { endpoint: "https://service.test", nested: [true, null, 3] },
      env: "SERVICE_CONFIG",
      kind: "derived-config",
      name: "service-config"
    }
  ],
  descriptor_digest: `sha256:${"a".repeat(64)}`,
  model_engine_auth: { from: "/tmp/codex", kind: "codex", profile: "launch" },
  run_id: "run-1",
  scope: "world",
  selected_target: {
    fingerprint: `sha256:${"b".repeat(32)}`,
    handle: `opaque_${"c".repeat(16)}`,
    version: "spawnfile.target-resource.selected-target.v1"
  },
  version: CREDENTIAL_PROVISIONING_REQUEST_VERSION,
  world_bindings: {
    json_url: "https://world.test/v1/world",
    mcp_url: "https://world.test/mcp",
    members: [{
      id: "agent-alpha",
      principal_id: "agent:agent-alpha",
      token_credential_name: "agent-alpha-token"
    }],
    world_instance_id: "world-1"
  }
});
const reject = (raw: unknown) =>
  expect(() => parseCredentialProvisioningRequest(raw)).toThrow(TARGET_SECRET_SOURCE_ERROR);

describe("credential provisioning request", () => {
  it("accepts and freezes an exact declarative request", () => {
    const parsed = parseCredentialProvisioningRequest(request());
    expect(parsed.version).toBe(CREDENTIAL_PROVISIONING_REQUEST_VERSION);
    expect(parsed.credentials).toHaveLength(2);
    expect(parsed.world_bindings?.members[0]?.token_credential_name).toBe("agent-alpha-token");
    expect(Object.isFrozen(parsed)).toBe(true);
    expect(Object.isFrozen(parsed.credentials)).toBe(true);
  });

  it("parses noncanonical UTF-8 JSON bytes without preserving source text", () => {
    const bytes = new TextEncoder().encode(JSON.stringify(request(), null, 2));
    expect(parseCredentialProvisioningRequestBytes(bytes).run_id).toBe("run-1");
  });

  it("rejects unknown keys at every schema level and the wrong version", () => {
    const variants = [
      { ...request(), extra: true },
      { ...request(), credentials: [{ ...request().credentials[0], extra: true }] },
      { ...request(), selected_target: { ...request().selected_target, extra: true } },
      { ...request(), world_bindings: { ...request().world_bindings, extra: true } },
      {
        ...request(),
        world_bindings: {
          ...request().world_bindings,
          members: [{ ...request().world_bindings.members[0], extra: true }]
        }
      },
      { ...request(), model_engine_auth: { ...request().model_engine_auth, extra: true } },
      { ...request(), version: "spawnfile.auth.credential-provisioning.request.v2" }
    ];
    for (const variant of variants) reject(variant);
  });

  it("requires nonempty credentials with unique names and env names", () => {
    reject({ ...request(), credentials: [] });
    reject({
      ...request(),
      credentials: [request().credentials[0], { ...request().credentials[0], env: "OTHER_TOKEN" }]
    });
    reject({
      ...request(),
      credentials: [request().credentials[0], { ...request().credentials[0], name: "other-token" }]
    });
  });

  it.each(["TOKEN", "_TOKEN", "lower_token", "A-B", "A B", "1TOKEN"])(
    "rejects invalid env name %s",
    (env) => reject({ ...request(), credentials: [{ ...request().credentials[0], env }] })
  );

  it.each([15, 129, 16.5, Number.NaN, Number.POSITIVE_INFINITY])(
    "rejects invalid generated byte count %s",
    (bytes) => reject({ ...request(), credentials: [{ ...request().credentials[0], bytes }] })
  );

  it.each(["value", "secret", "token", "bearer", "password", "material"])(
    "accepts a clean graph and rejects forbidden key %s anywhere",
    (key) => {
      expect(parseCredentialProvisioningRequest(request()).credentials).toHaveLength(2);
      const raw = request();
      (raw.credentials[1]!.content as Record<string, unknown>)[key] = "smuggled";
      reject(raw);
    }
  );

  it("requires every world member token name to refer to a declared credential", () => {
    const raw = request();
    raw.world_bindings.members[0]!.token_credential_name = "absent";
    reject(raw);
  });

  it("rejects prototype pollution, accessors, and non-ordinary nested content", () => {
    const polluted = request();
    Object.setPrototypeOf(polluted.credentials[1]!.content, { injected: true });
    reject(polluted);

    const accessed = request();
    Object.defineProperty(accessed.credentials[1]!.content, "endpoint", {
      enumerable: true,
      get: () => "SENTINEL"
    });
    reject(accessed);
  });
});
